---
# tasks file for deploy
- name: Update cache
  apt:
    update_cache: yes

- name: Install depends
  apt:
    pkg:
      - ca-certificates
      - curl

- name: Copy docker-compose file
  copy:
    src: files/docker-compose.yml
    dest: /home/{{ ansible_user }}/docker-compose.yml

- name: Copy Dockerfile
  copy:
    src: files/Dockerfile
    dest: /home/{{ ansible_user }}/Dockerfile



