version: '3.5'

services:
  mydocker:
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -f /dev/null # Чтобы контейнер оставался активным.
    stdin_open: true # Устанавливает интерактивный режим для стандартного ввода (stdin).
    container_name: mydocker
    volumes:
      - /home/neutron/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/neutron/www/index.php:/sites/index.php
    ports:
      - "80:80"
    networks:
      - my_network
    restart: unless-stopped
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
    - my_network

volumes:
  mysql_data:

networks:
  my_network: