---
# tasks file for php
- name: www create
  file:
    path: /home/{{ ansible_user }}/www
    state: directory
    mode: '0755'

- name: Generate index.php
  copy:
    content: |
      <?php
      ini_set("display_startup_errors", 1);
      ini_set("display_errors", 1);
      ini_set("html_errors", 1);
      ini_set("log_errors", 1);
      error_reporting(E_ERROR | E_PARSE | E_WARNING);
      $con = mysqli_connect('mysql', 'root', 'root', 'my_db');

      if (!$con) {
          die("Connection failed: " . mysqli_connect_error());
      }
      echo "Connection Successful";
      ?>
    dest: /home/{{ ansible_user }}/www/index.php